# Generated by Django 6.0.4 on 2026-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kiota ', max_length=100)),
                ('logo', models.ImageField(help_text='Upload company logo', upload_to='company/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(help_text='Format: 254700000000', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('about_description', models.TextField()),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
