# Generated by Django 6.0.4 on 2026-04-10 22:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiota', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(help_text='Upload company logo', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Kiota', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_main',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
