# Generated by Django 6.0.4 on 2026-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiota', '0004_alter_companyprofile_logo_alter_companyprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
